### ISSUE TITLE
5주 - 사용자 평가 및 사용자 계정 제거 기능 [유다빈]

### ISSUE THREAD

**Issue by Alisherka7** [StyleRent/BackEnd-SpringBoot#5]

**Comment by ddabi** [comment]
> ### **Rank Entity 생성**

![image](https://user-images.githubusercontent.com/115603720/231233121-b3a3d251-9956-4653-a7c6-fa6799c1e673.png)
rank(평점)은 1~5점까지로 설정하였다.
@ManyToOne : user 및 receiver 필드가 User 엔티티와의 다대일 관계를 나타내는 것을 지정한다.

> ### **RankDto 생성**

![image](https://user-images.githubusercontent.com/115603720/231235076-fb28fb0d-8dfb-4401-bed4-3817686951bf.png)

> ### **RankResponseDto 생성**

![image](https://user-images.githubusercontent.com/115603720/231235451-d72be92a-16b2-486a-a92b-ac4bc364f063.png)

> ### **RankRepository 생성**
![image](https://user-images.githubusercontent.com/115603720/231236057-925ecbab-77e8-41c0-af91-2c4e1f6f9283.png)
12~13 : 데이터베이스에서 일치하는 레코드가 없는 경우 Rank 객체 또는 null을 반환
15~16 : 데이터베이스에서 일치하는 레코드가 없는 경우 Rank 객체 또는 null을 반환
13 : findById는 user_id로 Rank 객체를 검색하는 데 사용된다.
16 : checkUnique는 주어진 user_id와 receiver_id 조합에 대해 데이터베이스에 Rank 객체가 존재하는지 확인하는 데 사용된다. receiverId는 각각 currentId와 receiverId 매개변수의 값을 전달하는 데 사용된다. 이 메소드는 데이터베이스에 객체가 있으면 Rank 객체를 포함하는 Optional 객체를 반환하고, 객체가 없으면 빈(null) Optional 객체를 반환한다. 

> ### **RankService 생성**
![image](https://user-images.githubusercontent.com/115603720/231238583-8e1b43d3-2dd8-4f6a-b7aa-590a64d96e7b.png)
![image](https://user-images.githubusercontent.com/115603720/231238690-72eb47d4-b302-42a1-9267-5b7db93ec9b9.png)
![image](https://user-images.githubusercontent.com/115603720/231238804-c1328d25-d87b-4922-b360-000485ae4b94.png)
32,38,44,50 : 각각에 맞는 오류 메시지를 출력 한다. (아이디가 존재하지 않는다면 평가할 수 없다. 한번 평가한 아이디는 다시 평가하지 못한다. 내 아이디는 내가 평가할 수 없다.)
56~70 : 새로운 Rank 객체를 생성하고 데이터베이스에 저장한 뒤, 해당하는 RankResponse 객체를 반환한다.

> ### **RankController 생성**
![image](https://user-images.githubusercontent.com/115603720/231239971-7bdd4614-ecb5-4028-90c8-2bb89ac13461.png)

**Comment by ddabi** [comment]
### **결과확인**
![image](https://user-images.githubusercontent.com/115603720/231241291-c6669e71-7b32-4b1f-9727-9e37316a7e87.png)
사용자들을 localhost user table에서 확인함

- A가 B를 평가했을 경우

![image](https://user-images.githubusercontent.com/115603720/231241746-327805ed-f503-45cb-9f07-0fa0c4491ff1.png)
![image](https://user-images.githubusercontent.com/115603720/231241936-f0931052-08f2-48c8-95b0-46ac48a85c2e.png)
2번 토큰으로 send한다.
![image](https://user-images.githubusercontent.com/115603720/231242062-a56f6b75-ea0c-4e32-89c8-0976a984ee67.png)
2번이 1번에게 4점을 준 것이 정상적으로 저장 되었음을 확인할 수 있다.

- A가 B를 중복 평가했을 경우
![image](https://user-images.githubusercontent.com/115603720/231242892-86cd99f5-6363-4f1a-a1b6-7684acf96182.png)
![image](https://user-images.githubusercontent.com/115603720/231242794-01d22438-ae81-49c0-8b2d-a38974226e8d.png)
2번 토큰으로 send한다.
![image](https://user-images.githubusercontent.com/115603720/231243037-74cffcf9-6708-4c41-b9fc-cfa189ba5cb8.png)
중복 평가 이므로 '이미 평가된 사용자 입니다.'라는 문구가 출력이 되고, rank table에도 결과가 업데이트 되지 않았다.

- C가 자기 자신을 평가했을 경우
![image](https://user-images.githubusercontent.com/115603720/231243654-87cbf46b-6e06-42e5-b830-c9744b1ef5ba.png)
![image](https://user-images.githubusercontent.com/115603720/231243733-5ab79158-f277-4cc0-af1a-bebbedcb3c4d.png)
3번 토큰으로 send
![image](https://user-images.githubusercontent.com/115603720/231243951-3da5c7d0-d3a5-48df-a16b-44fdd3b125ab.png)
자기 자신을 평가 하였으므로 '평가 할 수 없는 아이디입니다.' 라는 문구가 출력되고,  rank table에도 결과가 업데이트 되지 않았다.

- 존재하지 않는 사용자를 평가했을 경우
